on: [push, pull_request]
jobs:
  front-deployment:
    name: Front-Deployment

    runs-on: ${{ matrix.os }}

    if: contains('refs/heads/main', github.ref)

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Generate
        run: npm run generate
        working-directory: frontend

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
